---
title: "Rito_Fabio_EC_118"
author: "Sdelci Lab"
date: "`r Sys.Date()`"
output:
    html_document:
      code_folding: hide
      toc: true
      toc_depth: 2
      highlight: tango
knit: (function(inputFile, encoding) { rmarkdown::render(inputFile, encoding = encoding, output_file = file.path(dirname(inputFile), 'Rito_Fabio_EC_118.html')) })

---
Always to change: File_name [done], Source [done], Conditions [done], Sample_n [done], title [done]

```{r setup_packages,  echo=FALSE, cache=FALSE, warning= FALSE, message=FALSE}
method = "classical DDA"
output_folder = here::here("Output","EC_118")

pacman::p_load("knitr","readr","tidyverse", "openxlsx", "stringr",
               "data.table","BiocManager","openxlsx","factoextra", "devtools",
               "DescTools", "UpSetR", "magick", "proteus","SubCellBarCode")

source_file_name <- here::here("Codes",
                               "functions.R")
source(source_file_name)

file_parsed = parse(source_file_name) %>% 
    Filter(is_function, .)  
unlist(Map(function_name, file_parsed))

## Global options
options(max.print="75")
opts_chunk$set(cache=FALSE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
#opts_knit$set(root.dir = "./../")
```

```{r loading_maxquant, fig.width = 14, fig.height=14}
txt_folder <-  here::here("Datasets","Raw",
                            "EC_118",
                            "txt")
Quality_Control(txt_folder)

columns_to_keep = c("Majority protein IDs",
                    "LFQ intensity","Potential","Reverse")

Samples_df <- data.frame(order = 1:12 %>% as.character() %>% paste0(" ",.),
                         raw = c("P11906","P11907","P11908","P11909","P11910","P11911","P11912","P11913","P11914","P11915","P11916","P11917"),
                         sample = c(paste0("N_UC_",1:3),
                                    paste0("N_C_",1:3),
                                    paste0("C_C_",1:3),
                                    paste0("C_UC_",1:3)))
                         

Data_matrix <- fread(here::here(txt_folder,
                            "proteinGroups.txt")) %>%
  dplyr::select(matches(paste(columns_to_keep, collapse = "|"))) %>% 
  set_names(.,str_replace_all(colnames(.),Samples_df %>% pull(sample,order) %>% rev())) %>% 
  janitor::clean_names() %>% 
  subset(!((reverse == "+") | (potential_contaminant == "+"))) %>% 
  dplyr::select(-c(reverse,potential_contaminant)) %>% 
  mutate(majority_protein_i_ds  = str_remove_all(majority_protein_i_ds,";[:graph:]*")) %>% 
  column_to_rownames("majority_protein_i_ds") %>% 
  mutate(across(everything(),~na_if(.x,0))) %>% 
  set_names(.,str_remove_all(colnames(.),"lfq_intensity_")) %>% 
  glimpse()
HUMAN_9606 <- read_tsv(here::here("Datasets","Raw", "HUMAN_9606_idmapping.dat"),
                 col_names = FALSE) %>% 
  set_names(c("Uniprot","Type","ID"))

DEP_data <- DEP_DDA(Data_matrix,"Rito_Fabio_EC_118")
Data_matrices <- map(.x = 1:2,
                   ~openxlsx::read.xlsx(here::here("Datasets","Processed", "Rito_Fabio_EC_118matrices.xlsx"), sheet = .x, rowNames = T)) %>% 
  set_names(getSheetNames(here::here("Datasets","Processed", "Rito_Fabio_EC_118matrices.xlsx")))  


Volcano_DFs <- map(.x = 1:2,
                   ~openxlsx::read.xlsx(here::here("Datasets","Processed", "Rito_Fabio_EC_118volcano_DFs.xlsx"), sheet = .x)) %>% 
  set_names(getSheetNames(here::here("Datasets","Processed", "Rito_Fabio_EC_118volcano_DFs.xlsx")))
Significant_proteins <- c(Volcano_DFs$c_c_vs_c_uc_diff %>% 
                            subset(p.adj<0.05) %>% 
                            pull(Uniprot),
                          Volcano_DFs$n_c_vs_n_uc_diff %>% 
                            subset(p.adj<0.05) %>% 
                            pull(Uniprot) ) %>% unique()

ego2 <- gseGO(geneList     = Volcano_DFs$c_c_vs_c_uc_diff %>% pull(log2_FC, Uniprot) %>% sort(decreasing = T) ,
                 OrgDb        = org.Hs.eg.db,
                 ont          = "ALL",
                 keyType = "UNIPROT",
                 #nPerm        = 1000,
                 minGSSize    = 50,
                 maxGSSize    = 500,
                 pvalueCutoff = 0.05,
                 verbose      = FALSE)
   if((ego2@result %>% nrow)>0){
       enrichplot::ridgeplot(ego2)+ ggtitle(glue::glue("c_c_vs_c_uc_diff ALL-GSEA"))
       ggsave(here::here("Output","EC_118" , glue::glue("c_c_vs_c_uc_diff","DDA_118", "ALL-GSEA.png")), height = 20, width  = 15)}
  ego3 <- gseGO(geneList     = Volcano_DFs$n_c_vs_n_uc_diff %>% pull(log2_FC, Uniprot) %>% sort(decreasing = T) ,
                 OrgDb        = org.Hs.eg.db,
                 ont          = "ALL",
                 keyType = "UNIPROT",
                 #nPerm        = 1000,
                 minGSSize    = 50,
                 maxGSSize    = 500,
                 pvalueCutoff = 0.05,
                 verbose      = FALSE)
   if((ego3@result %>% nrow)>0){
       enrichplot::ridgeplot(ego3, showCategory = 68)+
           ggtitle(glue::glue("n_c_vs_n_uc_diff"," ALL-GSEA"))
       ggsave(here::here("Output","EC_118", glue::glue("n_c_vs_n_uc_diff","DDA_118", "ALL-GSEA.png")), height = 20, width  = 15)}
   

```
```{r CORREP}
##### CORREP#####
Correp_correlation <- correp(Data_matrices$Imputted,Significant_proteins)
Correp_correlation$heatmap
rowMeans <- Data_matrices$Imputted %>% rowMeans()



clusters_df <- Data_matrices$Imputted %>% 
    mutate(across(everything(), ~.x-rowMeans)) %>% 
    rownames_to_column("gene") %>% 
    pivot_longer(-gene, names_to = "condition", values_to = "abundance") %>% 
    inner_join(Correp_correlation$clusters %>% enframe("gene","cluster")) %>% 
  mutate(cluster = as.character(cluster))



clusters_df_avg <- clusters_df %>% 
  group_by(condition,cluster) %>% 
  summarise(abundance = median(abundance))

level_order <- c("n_uc_1",  "n_uc_2", "n_uc_3",
                  "n_c_1",  "n_c_2",  "n_c_3",
                 "c_uc_1", "c_uc_2", "c_uc_3",
                 "c_c_1",  "c_c_2",  "c_c_3")

  ggplot(data=clusters_df,aes(x = factor(condition, level = level_order),  y= abundance, colour = cluster, group = gene))+
    geom_line(alpha = 0.1)+
    geom_point(alpha = 0.1)+
    facet_wrap("cluster")+
     geom_line(data=clusters_df_avg, aes(x=condition, y=abundance, group = cluster ), colour="grey10")+
    ggtitle("Cluster Behaviour from CORREP") +
    theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
    xlab("samples")
ggsave(here::here("Output", "EC_118","Significant Protein Clusters reordered RG.png"))



list_of_diff_genes <- clusters_df %>% 
  group_split(cluster) %>% 
  set_names(.,map_chr(.x = .,~paste0("cluster_",.x %>% pull(cluster) %>% unique()))) %>% 
  map(.x = .,~.x %>% pull(gene) %>% str_remove_all(";[:graph:]*$")%>% unique() )
enrich_clusters <- function(gene_list){
  enrichGO(gene         = gene_list,
           OrgDb         = org.Hs.eg.db,
           universe = rownames(Data_matrices$Imputted)%>% str_remove_all(";[:graph:]*$")%>% unique(),
           keyType       = 'UNIPROT',
           ont           = "BP",
           pAdjustMethod = "BH",
           pvalueCutoff  = 0.01,
           qvalueCutoff  = 0.05) 
}
ck2 <- compareCluster(geneCluster = list_of_diff_genes, fun = enrich_clusters)
dotplot(ck2)
ck2@compareClusterResult %>% 
  mutate(GeneRatio = sapply(strsplit(GeneRatio, split = "/"), function(x) as.numeric(x[1]) / as.numeric(x[2]))) %>%
  group_by(Cluster) %>% 
  arrange(p.adjust) %>% 
  slice(1:20) %>% 
  ggplot(aes(x = Cluster, y= Description, colour = p.adjust, size = GeneRatio))+
  geom_point()+
  ggtitle("CORREP Clusters Enrichment BP simplified")
ggsave(here::here("Output", "EC_118","Significant Protein Clusters ORA.png"))
```

